import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { TRPCReactProvider } from "@/trpc/client";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * RootLayout component wraps the entire app.
 * It provides global context providers and sets HTML structure.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Provide tRPC React context to enable remote procedure calls in the app
    <TRPCReactProvider>
      <html lang="en">
        <body className={`${inter.className} ${inter.className} antialiased`}>
          {/* Render all nested page components */}
          {children}
        </body>
      </html>
    </TRPCReactProvider>
  );
}
